appId: com.duckduckgo.mobile.ios
---

# Load constants
- runFlow:
    file: constants.yaml

- tapOn: ${output.settingsLabel}

- waitForAnimationToEnd

- tapOn: ${output.doneLabel}

- waitForAnimationToEnd
