name: DBP - PR Checks

defaults:
  run:
    working-directory: SharedPackages/DataBrokerProtectionCore

on:
  push:
    branches: [ main ]
    paths:
      - 'SharedPackages/DataBrokerProtectionCore/**'
  pull_request:
    paths:
      - '.github/**'
      - '.xcode-version'
      - 'SharedPackages/DataBrokerProtectionCore/**'
  schedule:
    - cron: '10,40 4,5,6 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  unit-tests:

      name: Run unit tests (macOS)

      runs-on: macos-15
      timeout-minutes: 30

      env:
        RUNS_ON: macos-15 # keep this in sync with runs-on above
        WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}

      outputs:
        commit_author: ${{ steps.fetch_commit_author.outputs.commit_author }}
        pr_reviewers: ${{ steps.fetch_commit_author.outputs.pr_reviewers }}

      steps:

      - name: Check out the code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Start measuring duration
        id: start-duration-macos
        uses: ./.github/actions/measure-duration
        with:
          mode: start

      - name: Set cache key hash
        run: |
          has_only_tags=$(jq '[ .pins[].state | has("version") ] | all' Package.resolved)
          if [[ "$has_only_tags" == "true" ]]; then
            # hashFiles does not respect the working directory, so the full path must be specified
            echo "cache_key_hash=${{ hashFiles('SharedPackages/DataBrokerProtectionCore/Package.resolved') }}" >> $GITHUB_ENV
          else
            echo "Package.resolved contains dependencies specified by branch or commit, skipping cache."
          fi

      - name: Cache SPM
        if: env.cache_key_hash
        uses: actions/cache@v4
        with:
          path: |
            SharedPackages/DataBrokerProtectionCore/.build/artifacts
            SharedPackages/DataBrokerProtectionCore/.build/checkouts
            SharedPackages/DataBrokerProtectionCore/.build/repositories
            SharedPackages/DataBrokerProtectionCore/.build/workspace-state.json
          key: ${{ runner.os }}-dbp-spm-${{ env.cache_key_hash }}
          restore-keys: |
            ${{ runner.os }}-dbp-spm-

      - name: Select Xcode
        uses: ./.github/actions/select-xcode-version

      - name: Configure system logging
        run: |
          sudo cp com.apple.system.logging.plist /Library/Preferences/Logging/com.apple.system.logging.plist
          sudo killall logd || true

      - name: Start log stream in background
        run: |
          log stream --debug --info --predicate 'process == "xctest" OR process == "swiftpm-xctest-helper"' --style syslog > xctest.log 2>&1 &
          echo $! > log_stream.pid

      - name: Build BSK
        run: set -o pipefail && swift build | tee build-log.txt | xcbeautify

      - name: Run tests
        id: run-unit-tests
        run: set -o pipefail && swift test | tee -a build-log.txt | xcbeautify --report junit --report-path . --junit-report-filename package-tests.xml

      - name: Report job duration
        if: success() || (always() && steps.run-unit-tests.outcome == 'failure')
        uses: ./.github/actions/measure-duration
        with:
          mode: stop
          start-timestamp: ${{ steps.start-duration-macos.outputs.start-timestamp }}
          pixel-name: m_ci_apple_duration_dbp_unit_tests_macos
          pixel-params: |
            runner: ${{ env.RUNS_ON }}

      - name: Stop log stream
        if: always()
        run: |
          if [ -f log_stream.pid ]; then
            kill $(cat log_stream.pid) || true
          fi

      - name: Upload XCTest log stream output
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dbp-xctest-log-stream.log
          path: |
            SharedPackages/DataBrokerProtectionCore/xctest.log
          retention-days: 7

      - name: Publish Unit Tests Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          check_name: DBP Test Report (macOS)
          report_paths: SharedPackages/DataBrokerProtectionCore/package-tests.xml
          require_tests: true
          check_retries: true

      - name: Send Unit Tests Status Pixel
        if: always() && github.ref_name == 'main'
        uses: ./.github/actions/send-pixel
        with:
          pixel-name: m_ci_apple_status_dbp_main_unit_tests_macos_${{ steps.run-unit-tests.outcome }}

      - name: Update Asana with failed unit tests
        if: always() # always run even if the previous step fails
        env:
          ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
          WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}
        run: |
          # Extract failed tests from the junit report
          # Only keep failures unique by classname and name (column 1 and 2 of the yq output)
          yq < package-tests.xml -p xml -o json -r \
            $'[.testsuites.testsuite[].testcase] | flatten | map(select(.failure) | .+@classname + " " + .+@name + " \'" + .failure.+@message + "\' ${{ env.WORKFLOW_URL }}") | .[]' \
            | sort -u -k 1,2 \
            | xargs -L 1 ${{ github.workspace }}/scripts/report-failed-unit-test.sh -s ${{ vars.APPLE_CI_FAILING_TESTS_DBP_FAILED_TESTS_SECTION_ID }}

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-log.txt
          path: SharedPackages/DataBrokerProtectionCore/build-log.txt

      - name: Wait for crash reports to be generated
        if: failure()
        run: |
          sleep 30
          ls -l ~/Library/Logs/DiagnosticReports

      - name: Upload crash reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "dbp-crash-reports-macOS"
          path: |
            ~/Library/Logs/DiagnosticReports/xctest-*.ips
          retention-days: 7
          if-no-files-found: ignore

      - name: Fetch latest commit author and PR reviewers
        if: failure() && github.ref_name == 'main' && github.run_attempt == 1
        id: fetch_commit_author
        uses: ./.github/actions/fetch-commit-info
        with:
          github-token: ${{ github.token }}

  unit-tests-ios:

      name: Run unit tests (iOS)

      runs-on: macos-15
      timeout-minutes: 30

      env:
        RUNS_ON: macos-15 # keep this in sync with runs-on above

      steps:

      - name: Check out the code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Start measuring duration
        id: start-duration-ios
        uses: ./.github/actions/measure-duration
        with:
          mode: start

      - name: Set cache key hash
        run: |
          has_only_tags=$(jq '[ .pins[].state | has("version") ] | all' Package.resolved)
          if [[ "$has_only_tags" == "true" ]]; then
            echo "cache_key_hash=${{ hashFiles('SharedPackages/DataBrokerProtectionCore/Package.resolved') }}" >> $GITHUB_ENV
          else
            echo "Package.resolved contains dependencies specified by branch or commit, skipping cache."
          fi

      - name: Cache SPM
        if: env.cache_key_hash
        uses: actions/cache@v4
        with:
          path: SharedPackages/DataBrokerProtectionCore/DerivedData/SourcePackages
          key: ${{ runner.os }}-dbp-spm-ios-${{ env.cache_key_hash }}
          restore-keys: |
            ${{ runner.os }}-dbp-spm-ios-

      - name: Select Xcode
        uses: ./.github/actions/select-xcode-version

      - name: Select iOS Simulator
        id: select-simulator
        uses: ./.github/actions/select-ios-simulator
        with:
          preferred-versions: "18.6,18.2"

      - name: Resolve package dependencies
        run: |
          echo "Using iOS simulator: ${{ steps.select-simulator.outputs.ios-version }}"
          echo "Destination: ${{ steps.select-simulator.outputs.destination }}"
          
          while xcodebuild -resolvePackageDependencies \
            -scheme DataBrokerProtectionCore-Package \
            -destination '${{ steps.select-simulator.outputs.destination }}' \
            -derivedDataPath DerivedData \
            2>&1 | grep Error; do :; done

          # you just can't have good things
          # set -o pipefail && swift package resolve | tee ios-build-log.txt | xcbeautify
          # mkdir -p DerivedData/SourcePackages
          # mv .build/* DerivedData/SourcePackages

      - name: Run tests
        id: run-unit-tests
        run: |
          set -o pipefail && xcodebuild test \
            -scheme DataBrokerProtectionCore \
            -destination '${{ steps.select-simulator.outputs.destination }}' \
            -derivedDataPath DerivedData \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            -test-iterations 3 \
            -retry-tests-on-failure \
            CODE_SIGNING_ALLOWED=NO \
            | tee -a ios-build-log.txt \
            | xcbeautify --report junit --report-path . --junit-report-filename dbp-ios-unittests.xml

      - name: Report job duration
        if: success() || (always() && steps.run-unit-tests.outcome == 'failure')
        uses: ./.github/actions/measure-duration
        with:
          mode: stop
          start-timestamp: ${{ steps.start-duration-ios.outputs.start-timestamp }}
          pixel-name: m_ci_apple_duration_dbp_unit_tests_ios
          pixel-params: |
            runner: ${{ env.RUNS_ON }}

      - name: Publish Unit Tests Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          check_name: DBP Test Report (iOS)
          report_paths: SharedPackages/DataBrokerProtectionCore/dbp-ios-unittests.xml
          require_tests: true
          check_retries: true

      - name: Send Unit Tests Status Pixel
        if: always() && github.ref_name == 'main'
        uses: ./.github/actions/send-pixel
        with:
          pixel-name: m_ci_apple_status_dbp_main_unit_tests_ios_${{ steps.run-unit-tests.outcome }}

      - name: Update Asana with failed unit tests
        if: always() # always run even if the previous step fails
        env:
          ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
          WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}
        run: |
          # Extract failed tests from the junit report
          # Only keep failures unique by classname and name (column 1 and 2 of the yq output)
          yq < dbp-ios-unittests.xml -p xml -o json -r \
            $'[.testsuites.testsuite[].testcase] | flatten | map(select(.failure) | .+@classname + " " + .+@name + " \'" + .failure.+@message + "\' ${{ env.WORKFLOW_URL }}") | .[]' \
            | sort -u -k 1,2 \
            | xargs -L 1 ${{ github.workspace }}/scripts/report-failed-unit-test.sh -s ${{ vars.APPLE_CI_FAILING_TESTS_DBP_FAILED_TESTS_SECTION_ID }}

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ios-build-log.txt
          path: SharedPackages/DataBrokerProtectionCore/ios-build-log.txt

      - name: Wait for crash reports to be generated
        if: failure()
        run: |
          sleep 30
          ls -l ~/Library/Logs/DiagnosticReports

      - name: Upload crash reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "dbp-crash-reports-iOS"
          path: |
            ~/Library/Logs/DiagnosticReports/xctest-*.ips
          retention-days: 7
          if-no-files-found: ignore

  create-asana-task:
    name: Create Asana Task
    needs: [unit-tests, unit-tests-ios]

    if: failure() && github.ref_name == 'main' && github.run_attempt == 1

    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Create Asana Task
        uses: ./.github/actions/asana-failed-pr-checks
        with:
          action: create-task
          asana-access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-section-id: ${{ vars.APPLE_CI_FAILING_TESTS_BSK_POST_MERGE_SECTION_ID }}
          commit-author: ${{ needs.unit-tests.outputs.commit_author }}
          pr-reviewers: ${{ needs.unit-tests.outputs.pr_reviewers }}
          github-token: ${{ secrets.GH_RO_PAT }}

  close-asana-task:
    name: Close Asana Task
    needs: [unit-tests, unit-tests-ios]

    if: success() && github.ref_name == 'main' && github.run_attempt > 1

    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Close Asana Task
        uses: ./.github/actions/asana-failed-pr-checks
        with:
          action: close-task
          asana-access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-section-id: ${{ vars.APPLE_CI_FAILING_TESTS_BSK_POST_MERGE_SECTION_ID }}
          github-token: ${{ secrets.GH_RO_PAT }}
