name: iOS - Code Freeze

defaults:
  run:
    working-directory: iOS

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New release version (calculated automatically if not provided)"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  create_release_branch:

    name: Create Release Branch

    runs-on: macos-15-xlarge
    timeout-minutes: 10

    outputs:
      release_branch_name: ${{ steps.make_release_branch.outputs.release_branch_name }}
      asana_task_url: ${{ steps.make_release_branch.outputs.asana_task_url }}

    steps:

      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Assert main branch
        run: |
          if [ "${{ github.ref_name }}" != "main" ]; then
            echo "👎 Not the main branch"
            exit 1
          fi

      - name: Setup Ruby and dependencies
        uses: ./.github/actions/setup-ruby
        with:
          working-directory: iOS
          cache-key-prefix: ios-ruby

      - name: Make release branch
        id: make_release_branch
        env:
          ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          bundle exec fastlane run start_new_release \
            platform:"ios" \
            version:"${{ inputs.version }}" \
            github_handle:"${{ github.actor }}" \
            target_section_id:"${{ vars.IOS_APP_BOARD_VALIDATION_SECTION_ID }}"

  run_tests:
    name: Run Tests

    needs: create_release_branch
    uses: ./.github/workflows/ios_pr_checks.yml
    with:
      branch: ${{ needs.create_release_branch.outputs.release_branch_name }}
      skip-release: true
    secrets: inherit

  prepare_release:
    name: Prepare Release
    needs: [ create_release_branch, run_tests ]
    uses: ./.github/workflows/ios_release.yml
    with:
      asana-task-url: ${{ needs.create_release_branch.outputs.asana_task_url }}
      branch: ${{ needs.create_release_branch.outputs.release_branch_name }}
    secrets: inherit

  tag_and_merge:
    name: Tag and Merge Branch
    needs: [ create_release_branch, prepare_release ]
    uses: ./.github/workflows/ios_tag_release_update_asana.yml
    with:
      asana-task-url: ${{ needs.create_release_branch.outputs.asana_task_url }}
      branch: ${{ needs.create_release_branch.outputs.release_branch_name }}
      release-type: internal
    secrets: inherit