name: iOS - Promote TestFlight to App Store

defaults:
  run:
    working-directory: iOS

on:
  workflow_dispatch:
    inputs:
      freeze-release:
        description: "Freeze the release branch"
        type: boolean
        default: true

jobs:
  promote-testflight-to-appstore:
    runs-on: macos-15

    steps:
    - name: Check out the code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
        sparse-checkout: |
          .github
          iOS/Gemfile
          iOS/Gemfile.lock
          iOS/fastlane
          iOS/scripts

    - name: Setup Ruby and dependencies
      uses: ./.github/actions/setup-ruby
      with:
        working-directory: iOS
        cache-key-prefix: ios-ruby

    - name: Promote TestFlight to App Store
      env:
        APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
        APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        APPLE_API_KEY_ISSUER: ${{ secrets.APPLE_API_KEY_ISSUER }}
      run: |
        git config --global user.name "Dax the Duck"
        git config --global user.email "dax@duckduckgo.com"
        bundle exec fastlane promote_latest_testflight_to_appstore

    - name: Freeze the release branch
      if: ${{ github.event.inputs.freeze-release == 'true' }}
      run: |
        bundle exec fastlane run freeze_release_branch \
          platform:ios \
          github_token:"${{ secrets.GITHUB_TOKEN }}"
