name: iOS - Sync-End-to-End tests

defaults:
  run:
    working-directory: iOS

on:
  schedule:
    - cron: '0 1 * * *' # run at 1 AM UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-for-sync-end-to-end-tests:
    name: Build for Sync End To End Tests
    runs-on: macos-15
    timeout-minutes: 30

    env:
      RUNS_ON: macos-15

    steps:
    - name: Check out the code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Start measuring duration
      id: start-duration
      uses: ./.github/actions/measure-duration
      with:
        mode: start

    - name: Set cache key hash
      run: |
         has_only_tags=$(jq '[ .pins[].state | has("version") ] | all' DuckDuckGo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved)
         if [[ "$has_only_tags" == "true" ]]; then
           echo "cache_key_hash=${{ hashFiles('iOS/DuckDuckGo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}" >> $GITHUB_ENV
         else
           echo "Package.resolved contains dependencies specified by branch or commit, skipping cache."
         fi

    - name: Cache SPM
      if: env.cache_key_hash
      uses: actions/cache@v4
      with:
        path: iOS/DerivedData/SourcePackages
        key: ${{ runner.os }}-ios-${{ env.cache_key_hash }}
        restore-keys: |
          ${{ runner.os }}-ios-

    - name: Select Xcode
      uses: ./.github/actions/select-xcode-version

    - name: Select iOS Simulator
      id: select-simulator
      uses: ./.github/actions/select-ios-simulator
      with:
        preferred-versions: "18.6,18.2"

    - name: Build for tests
      run: |
        echo "Using iOS simulator: ${{ steps.select-simulator.outputs.ios-version }}"
        echo "Destination: ${{ steps.select-simulator.outputs.destination }}"
        
        set -o pipefail && xcodebuild \
          -scheme "iOS Browser" \
          -destination "${{ steps.select-simulator.outputs.destination }}" \
          -derivedDataPath "DerivedData" \
          -skipPackagePluginValidation \
          -skipMacroValidation \
          ONLY_ACTIVE_ARCH=NO \
        | tee xcodebuild.log

    - name: Report job duration
      uses: ./.github/actions/measure-duration
      with:
        mode: stop
        start-timestamp: ${{ steps.start-duration.outputs.start-timestamp }}
        pixel-name: m_ci_apple_duration_ios_sync_tests_build
        pixel-params: |
          runner: ${{ env.RUNS_ON }}

    - name: Store Binary
      uses: actions/upload-artifact@v4
      with:
        name: duckduckgo-ios-app
        path: iOS/DerivedData/Build/Products/Debug-iphonesimulator/DuckDuckGo.app

    - name: Upload logs when workflow failed
      uses: actions/upload-artifact@v4
      if: failure() || cancelled()
      with:
        name: BuildLogs
        path: |
          iOS/xcodebuild.log
          iOS/DerivedData/Logs/Test/*.xcresult
        retention-days: 7

  sync-end-to-end-tests:
    name: Sync End To End Tests
    needs: build-for-sync-end-to-end-tests
    runs-on: macos-15

    env:
      RUNS_ON: macos-15 # keep this in sync with runs-on above

    timeout-minutes: 240

    steps:
    - name: Check out the code
      uses: actions/checkout@v4 # Don't need submodules here as this is only for the tests folder

    - name: Start measuring duration
      id: start-duration
      uses: ./.github/actions/measure-duration
      with:
        mode: start

    - name: Create test account for Sync and return the recovery code
      uses: duckduckgo/sync_crypto/action@main
      id: sync-recovery-code
      with:
        debug: true

    - name: Retrieve Binary
      uses: actions/download-artifact@v4
      with:
        name: duckduckgo-ios-app
        path: iOS/DerivedData/Build/Products/Debug-iphonesimulator/DuckDuckGo.app

    - name: Overwrite default config with sync one
      run: |
        cp ../.maestro/config-sync ../.maestro/config.yaml

    - name: Sync e2e tests
      id: upload
      uses: mobile-dev-inc/action-maestro-cloud@v1.9.8
      with:
        api-key: ${{ secrets.ROBIN_API_KEY }}
        project-id: ${{ vars.ROBIN_PROJECT_KEY }}
        name: sync_${{ github.sha }}
        timeout: 240
        app-file: iOS/DerivedData/Build/Products/Debug-iphonesimulator/DuckDuckGo.app
        workspace: .maestro
        include-tags: sync
        env: |
          ONBOARDING_COMPLETED=true
          CODE=${{ steps.sync-recovery-code.outputs.recovery-code }}
        device-os: iOS-18-2
        device-model: iPhone-16

    - name: Reset config
      run: |
        git checkout ../.maestro/config.yaml

    - name: Report job duration
      if: success() || (always() && steps.upload.outcome == 'failure')
      uses: ./.github/actions/measure-duration
      with:
        mode: stop
        start-timestamp: ${{ steps.start-duration.outputs.start-timestamp }}
        pixel-name: m_ci_apple_duration_ios_18_sync_tests
        pixel-params: |
          runner: ${{ env.RUNS_ON }}

  notify-failure:
    name: Notify on failure
    if: ${{ always() && contains(join(needs.*.result, ','), 'failure') && github.ref_name == 'main' }}
    needs: [build-for-sync-end-to-end-tests, sync-end-to-end-tests]
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4
    - name: Create Asana task when workflow failed
      run: |
        curl -s "https://app.asana.com/api/1.0/tasks" \
          --header "Accept: application/json" \
          --header "Authorization: Bearer ${{ secrets.ASANA_ACCESS_TOKEN }}" \
          --header "Content-Type: application/json" \
          --data ' { "data": { "name": "GH Workflow Failure - Sync End to end tests", "workspace": "${{ vars.ASANA_WORKSPACE_ID }}", "projects": [ "${{ vars.GH_ASANA_IOS_APP_PROJECT_ID }}" ], "notes" : "The end to end workflow has failed. See https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" } }'
