name: macOS - Prepare Release

defaults:
  run:
    working-directory: macOS

on:
  workflow_dispatch:
    inputs:
      asana-task-url:
        description: "Asana release task URL"
        required: true
        type: string
      skip-appstore:
        description: "Skip App Store release and only make a DMG build"
        default: false
        type: boolean
      destination:
        description: "Upload destination (TestFlight or App Store)"
        default: testflight
        type: string
  workflow_call:
    inputs:
      asana-task-url:
        description: "Asana release task URL"
        required: true
        type: string
      branch:
        description: "Branch name"
        required: false
        type: string
      skip-appstore:
        description: "Skip App Store release and only make a DMG build"
        default: false
        type: boolean
      destination:
        description: "Upload destination (TestFlight or App Store)"
        default: testflight
        type: string
    secrets:
      APPLE_API_KEY_BASE64:
        required: true
      APPLE_API_KEY_ID:
        required: true
      APPLE_API_KEY_ISSUER:
        required: true
      ASANA_ACCESS_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_ACCESS_KEY_ID_RELEASE_S3:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY_RELEASE_S3:
        required: true
      MATCH_PASSWORD:
        required: true
      MM_WEBHOOK_URL:
        required: true
      SSH_PRIVATE_KEY_FASTLANE_MATCH:
        required: true

jobs:

  dmg-release:
    name: Prepare DMG Release
    uses: ./.github/workflows/macos_build_notarized.yml
    with:
      release-type: release
      create-dmg: true
      asana-task-url: ${{ inputs.asana-task-url }}
      branch: ${{ inputs.branch }}
    secrets: inherit

  appstore-release:
    name: Prepare AppStore Release

    if: inputs.skip-appstore != 'true'

    uses: ./.github/workflows/macos_build_appstore.yml
    with:
      destination: ${{ inputs.destination }}
      asana-task-url: ${{ inputs.asana-task-url }}
      branch: ${{ inputs.branch }}
    secrets: inherit
