name: macOS - PIR E2E Tests

defaults:
  run:
    working-directory: macOS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1-5' # 3AM UTC offsetted to legacy to avoid action-junit-report@v4 bug
  push:
    branches: [ main, "release/macos/**", "hotfix/macos/**" ]
    paths:
      - 'SharedPackages/**'
      - 'macOS/**'
  pull_request:
    paths:
      - '.github/**'
      - '.xcode-version'
      - 'SharedPackages/**'
      - 'macOS/**'

jobs:
  pir-e2e-tests:
    name: PIR e2e tests
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-15-xlarge]
        include:
          - xcode-version: "16.4"
            runner: macos-15-xlarge

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.runner }}
      cancel-in-progress: true

    timeout-minutes: 32
    steps:
    - name: Register SSH keys for certificates repository and PIR fake broker repository access
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: |
                        ${{ secrets.SSH_PRIVATE_KEY_FASTLANE_MATCH }}
                        ${{ secrets.SSH_PRIVATE_KEY_PIR_FAKE_BROKER }}

    - name: Check out the code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Start measuring duration
      id: start-duration
      uses: ./.github/actions/measure-duration
      with:
        mode: start

    - name: Check out the PIR fake broker code
      uses: actions/checkout@v4
      with:
        repository: DuckDuckGo/pir-fake-broker
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY_PIR_FAKE_BROKER }}
        ref: main
        path: macOS/pir-fake-broker

    - name: Update Homebrew
      run: brew update

    - name: Start PIR Fake Broker
      run: |
        cd pir-fake-broker
        cd scripts
        ./install-prerequisites.sh
        ./setup-ci.sh
        cd ..
        pnpm start:all &

    - name: Setup Ruby and dependencies
      uses: ./.github/actions/setup-ruby
      with:
        working-directory: macOS
        cache-key-prefix: macos-ruby

    - name: Sync code signing assets
      id: sync-signing-first-attempt
      continue-on-error: true
      env:
        APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
        APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        APPLE_API_KEY_ISSUER: ${{ secrets.APPLE_API_KEY_ISSUER }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        SSH_PRIVATE_KEY_FASTLANE_MATCH: ${{ secrets.SSH_PRIVATE_KEY_FASTLANE_MATCH }}
      run: bundle exec fastlane sync_signing_ci

    - name: Retry sync code signing assets
      if: steps.sync-signing-first-attempt.outcome == 'failure'
      env:
        APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
        APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        APPLE_API_KEY_ISSUER: ${{ secrets.APPLE_API_KEY_ISSUER }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        SSH_PRIVATE_KEY_FASTLANE_MATCH: ${{ secrets.SSH_PRIVATE_KEY_FASTLANE_MATCH }}
      run: |
        echo "First attempt to sync code signing assets failed. Retrying..."
        bundle exec fastlane sync_signing_ci

    - name: Download and unzip artifact
      uses: actions/download-artifact@v4

    - name: Set cache key hash
      run: |
        has_only_tags=$(jq '[ .pins[].state | has("version") ] | all' DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved)
        if [[ "$has_only_tags" == "true" ]]; then
          echo "cache_key_hash=${{ hashFiles('macOS/DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}" >> $GITHUB_ENV
        else
          echo "Package.resolved contains dependencies specified by branch or commit, skipping cache."
        fi

    - name: Cache SPM
      if: env.cache_key_hash
      uses: actions/cache@v4
      with:
        path: macOS/DerivedData/SourcePackages
        key: ${{ runner.os }}-macos-${{ env.cache_key_hash }}
        restore-keys: |
          ${{ runner.os }}-macos-

    - name: Select Xcode
      uses: ./.github/actions/select-xcode-version
      with:
        xcode-version: ${{ matrix.xcode-version }}

    - name: Run PIR e2e Tests
      id: run-tests
      run: |
        launchctl setenv PRIVACYPRO_STAGING_TOKEN '${{ secrets.PRIVACYPRO_STAGING_TOKEN }}'
        set -o pipefail && xcodebuild test \
          -scheme "macOS PIR E2E Tests" \
          -derivedDataPath "DerivedData" \
          -configuration "CI" \
          -skipPackagePluginValidation -skipMacroValidation \
          ENABLE_TESTABILITY=true \
          "-only-testing:DBPE2ETests" \
          -retry-tests-on-failure \
          -test-iterations 2 \
          | tee xcodebuild.log \
          | tee pir-e2e-tests.log
      env:
          PRIVACYPRO_STAGING_TOKEN: ${{ secrets.PRIVACYPRO_STAGING_TOKEN }}

    - name: Report job duration
      if: success() || (always() && steps.run-tests.outcome == 'failure')
      uses: ./.github/actions/measure-duration
      with:
        mode: stop
        start-timestamp: ${{ steps.start-duration.outputs.start-timestamp }}
        pixel-name: m_ci_apple_duration_macos_pir_e2e_tests
        pixel-params: |
          runner: ${{ matrix.runner }}

    - name: Prepare test report
      if: always()
      run: |
        xcbeautify --report junit --report-path . --junit-report-filename pir-e2e-tests.xml < pir-e2e-tests.log

    - name: Publish tests report
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        check_name: "Test Report ${{ matrix.runner }}"
        report_paths: macOS/pir-e2e-tests.xml
        check_retries: true

    - name: Upload logs when workflow failed
      uses: actions/upload-artifact@v4
      if: failure() || cancelled()
      with:
        name: "BuildLogs ${{ matrix.runner }}"
        path: |
          macOS/xcodebuild.log
          macOS/DerivedData/Logs/Test/*.xcresult
          ~/Library/Logs/DiagnosticReports/*
        retention-days: 7

  notify-failure:
    name: Notify on failure
    if: ${{ always() && github.event_name == 'schedule' && (needs.pir-e2e-tests.result == 'failure' || needs.pir-e2e-tests.result == 'cancelled') }}
    needs: [pir-e2e-tests]
    runs-on: ubuntu-latest

    steps:
    - name: Create Asana task when workflow failed
      uses: duckduckgo/native-github-asana-sync@v1.1
      with:
        action: create-asana-task
        asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
        asana-project: ${{ vars.MACOS_APP_DEVELOPMENT_ASANA_PROJECT_ID }}
        asana-task-name: GH Workflow Failure - PIR e2e Tests
        asana-task-description: The PIR e2e Tests workflow has failed. See https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}